server:
 port: 8091

---
spring:
 profiles: local
 data-source:
   url: jdbc:mysql://localhost:3306/hospital_db
   username: root
   password: Reyansh@1
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate:
   ddl-auto: update
  show-sql: true

 
